# Generated by Django 4.0 on 2023-08-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_announcement_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Category picture'),
        ),
    ]
