# Generated by Django 4.0 on 2023-08-02 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_teacher',
        ),
    ]
